---
title: "CFPB Complaints"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(DT)
library(kableExtra)
library(htmlwidgets)
library(htmltools)
library(readxl)

#make new data table to count the companies with most complaints

companies <- complaints %>%
  count(company) %>%
  arrange(desc(n)) %>%
  select(
    company, 
    numberofcomplaints = "n"
  )

#make new data table to count the states with the most complaints

states <- complaints %>%
  count(state) %>%
  arrange(desc(n)) %>%
  select(
    state,
    numberofcomplaints = "n"
  )
 
#make new data table to show the most common issues complained about

issues <- complaints %>%
  count(issue) %>%
  arrange(desc(n)) %>%
  select(
    issue,
    numberofcomplaints = "n"
  )



```

Companies With the Most Complaints
=====================================
To filter, click on the boxes at the top of the columns. To sort, use the up/down arrows by the column names.

Row {data-height=1000}
-----------------------------------------------------------------------
```{r}

datatable(companies,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons', 
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy','print')
          )) %>% 
      formatStyle(c("company", "numberofcomplaints"), fontWeight = 'bold') %>% 
      formatStyle(c("numberofcomplaints"), color = "darkblue") 




```

States With the Most Complaints
=====================================
To filter, click on the boxes at the top of the columns. To sort, use the up/down arrows by the column names.

Row {data-height=1000}
-----------------------------------------------------------------------

```{r}

datatable(states,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons', 
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy','print')
          )) %>% 
      formatStyle(c("state", "numberofcomplaints"), fontWeight = 'bold') %>% 
      formatStyle(c("numberofcomplaints"), color = "darkblue") 


```

Most Common Issues Complained About
=====================================
To filter, click on the boxes at the top of the columns. To sort, use the up/down arrows by the column names.

Row {data-height=1000}
-----------------------------------------------------------------------

```{r}

datatable(issues,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons', 
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy','print')
          )) %>% 
      formatStyle(c("issue", "numberofcomplaints"), fontWeight = 'bold') %>% 
      formatStyle(c("numberofcomplaints"), color = "darkblue") 



```

